#include<stdio.h>

void CountingBases(char *alphabet) {

  int i;
  int adenine = 0;
  int cytosine = 0;
  int guanine = 0;
  int uracyl = 0;
       
  for(i = 0; alphabet[i] != EOF; ++i) {
  
    if(alphabet[i] == 'A') {
      ++adenine;
    }
    if(alphabet[i] == 'C'){
      ++cytosine;
    }
    if(alphabet[i] == 'G') { 
      ++guanine;
    }
    if(alphabet[i] == 'U') {
      ++uracyl;
    } 
    /*    
    switch(alphabet[i])  { 
    case 'A': ++adenine;
      break;
    case 'C': ++cytosine;
      break;
    case 'G': ++guanine;
      break;
    default: ++uracyl;
      break;
         
    }
    */ 
  }
  printf("ACGU: %d %d %d %d \n", adenine, cytosine, guanine, uracyl);
}


int main() {
  int i;

  char m[] = "UCCCGCUAUCACGGAAAUGUCCAAAUUAGCUUUGACAUCAUGAGAUUAAUCCAUAUCGUGUAUGAGAGGUAGGCUCUGACGGAAUUCCACUCAACUGCUUAACACAGCGCGCUGCACUCGGAGGCACGCGGCCGUUUAGCGUUUUACAUUCACACAUCCCGUGCAGAUCCAGAGGUCCGCUAAACUAGACUUAAAGUUCCGUACUAGGCCCCACAGAUGAAAUGGGCUAGCAAUAGAAUAGUUUGGUGAUGACGAUUGGUUGGUCCGCGUCGGCGUUCCACGCCCUCAAAUUUCGGUCAAUACUGCACAGUAUUGUCAGAUUUUGAAUUCAAUCUCUACACCUCUAUGACUAGAACACUCCGUGACGCGAUUAUGUUUCACAAAGGAUUACUUCGAGGGAUACGUGACACAGCGGCCAGACUCUUCGCGAACACGGCGCGUAUCCACGCGCGAGAUAUCUUUCAGAGGGAGUAUCAAAAAUCUAACUCAAGUUAGUCCCAAGCUGUCUGUAAUGUCAUUCGUUCAAAGCCAAAAGUUGUGAACACUGGCAAAGGUCUGAUUACCCCGGGCGCCCCUUGGUGUCGAGAGUUUUAGCCACUAUGGAUUUGUUCGUCGAAAAACACAGCUAAGAGUGGGAUCUCGUAGCUGCUUCGUAGCACUUUAAUCGCUGGCUACCUUCCUAGCUGCGCGGCUAGAGUAAUGCUGUACGCCGGGUACUUGACCGGACUUGUCGUCGAGUCUUGGUAAUGGAGCGAUCAGGGCCUGUAAAUUCGCUCAAUAACAUUUAUUGACACGGUUUUCUCUGCCAGAGGGUAAGUCCAGCGAGGGGAGAAGGCCAGCCUACUCAGCCUGCAGCGAUGUUGUUUAGGUCAUCCUGUCUACGGGUCCCUGCAGUCACUCAGCAGUAUUGGUGGUGGGGAAUGUGCCUUAUUCCUUAUUGGUCGCACUCCGGAAAUGGAUAUGGAGCUUGCCACAGA";  
  //  printf("%s",m[2]);
  CountingBases(m);

 return 0;
}
