#include<stdio.h>

void RNA_Transcription(char *alphabet) {

  int i;

  for(i = 0; *(alphabet + i) != 0; ++i) {
  

    if(alphabet[i] == 'T') {
      alphabet[i] = 'U';
    } 

  }
  for(i = 0; *(alphabet + i) != 0; ++i) {
  printf("%c", alphabet[i]);
  }
}


int main() {
  int i;

  char m[] = {"AGGTTAGTGGTTTACTAATTCAGGACTTGCATTAGTTTCACCGGGCCTACGAATGGTGGACAAGCACAGCTGCGAAACACACGGAGACAAGTGTGGACCTAGGGTACAAACTGTTTGACCGGTTTTAGGTAACCATCCAGAGCCCTGGTTAACTATAGATATTATAGCGCAACGGGGAGTGTCCGCTGGTGACACACCAAGAGATGAAAGCAGTGCCTCTGGTCAAGGTCGGGTAGCTCCAGATTATCATTGTAATAGGTCTCCCGCCTAGACGAGACAGTCCAAATTATGGTCCTGCGTATCACATCACGGATAAAATTGCCGCTACATGAAATGGGTACGGGGCGAATCAGGGGCTCCCTACAACATATTAATGGTACTGGAGTCGAGGTGCTCCCTGCCGGTTAGCTTCTCAGCCCGCGCGTGTTGTGTTTCGGAAGCACACAAAACAATGACTAGATCGATCGCGGTCAGGAGTTCAAAAACTCAGGATGGTAGCGATGTCCGTGAAGTAAGCGTGTGGTTCAGAGTTACGCTTGAATTCTCCCGATACGTATGCGGTATCCTGGTAAGGCCGGGAACCAGCGCACTAATCGTGACCCACCGATTTGACCCGACCTGAGCAATGGGTGTTAGTCGCCAATCAAGAGGATAAACCGCGCCCATCCGGCTGAATCGGTCCGCATGGTCGCGAAATCAGCGGCTGGGCCTTCTGCCGTTTACTACGTGATAGTAAAGCGGTGTTGTACCAAGTTCTCGCAAGGCGACCTATTGTAGAAAAAGAGACAGCTGATGGGGACGGAGTGCTGCATCATTCTACCGGGTCGACCAACCGTCACGTTGGATAGTGAGCGCACAGGTAAGGTAGCTCTCCGCGTGTGCTTATGCTCATCGACCCGGAATCTTCCTACGACTACAGCCGCTTCAA"};  

  RNA_Transcription(m);

 return 0;
}
