#include<stdio.h>

int RNA_Transcription(char *alphabet) {

  int i;

  for(i = 0; *(alphabet + i) != 0; ++i) {
  

    if(alphabet[i] == 'T') {
      alphabet[i] = 'U';
    }
  
  }
  return alphabet;
}


int main() {
  int i;

  char m[] = {"AGGTTAGTGGTTTACTAATTCAGGACTTGCATTAGTTTCACCGGGCCTACGAATGGTGGACAAGCACAGCTGCGAAACACACGGAGACAAGTGTGGACCTAGGGTACAAACTGTTTGACCGGTTTTAGGTAACCATCCAGAGCCCTGGTTAACTATAGATATTATAGCGCAACGGGGAGTGTCCGCTGGTGACACACCAAGAGATGAAAGCAGTGCCTCTGGTCAAGGTCGGGTAGCTCCAGATTATCATTGTAATAGGTCTCCCGCCTAGACGAGACAGTCCAAATTATGGTCCTGCGTATCACATCACGGATAAAATTGCCGCTACATGAAATGGGTACGGGGCGAATCAGGGGCTCCCTACAACATATTAATGGTACTGGAGTCGAGGTGCTCCCTGCCGGTTAGCTTCTCAGCCCGCGCGTGTTGTGTTTCGGAAGCACACAAAACAATGACTAGATCGATCGCGGTCAGGAGTTCAAAAACTCAGGATGGTAGCGATGTCCGTGAAGTAAGCGTGTGGTTCAGAGTTACGCTTGAATTCTCCCGATACGTATGCGGTATCCTGGTAAGGCCGGGAACCAGCGCACTAATCGTGACCCACCGATTTGACCCGACCTGAGCAATGGGTGTTAGTCGCCAATCAAGAGGATAAACCGCGCCCATCCGGCTGAATCGGTCCGCATGGTCGCGAAATCAGCGGCTGGGCCTTCTGCCGTTTACTACGTGATAGTAAAGCGGTGTTGTACCAAGTTCTCGCAAGGCGACCTATTGTAGAAAAAGAGACAGCTGATGGGGACGGAGTGCTGCATCATTCTACCGGGTCGACCAACCGTCACGTTGGATAGTGAGCGCACAGGTAAGGTAGCTCTCCGCGTGTGCTTATGCTCATCGACCCGGAATCTTCCTACGACTACAGCCGCTTCAA"};  

  printf("%s", RNA_Transcription(m));

 return 0;
}
